# Generated by Django 3.2 on 2024-11-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCESFAM', '0003_auto_20241114_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('motivo_documento', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_documento', models.DateField()),
                ('valor_monetario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.institucion')),
            ],
        ),
    ]
