# Generated by Django 3.2 on 2024-11-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCESFAM', '0003_auto_20241114_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')], max_length=50)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('motivo_documento', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_documento', models.DateField()),
                ('valor_monetario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.TextField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.documento')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.institucion')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.institucion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.institucion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.documento'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.institucion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='asignacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.asignacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='institucion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.institucion'),
            preserve_default=False,
        ),
    ]
