# Generated by Django 3.2 on 2024-11-28 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCESFAM', '0004_documento_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_documento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
