# Generated by Django 3.2 on 2024-11-28 08:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCESFAM', '0004_auto_20241128_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('direccion', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefono incorrecto. Ejemplo: +56912345678', regex='^(?:\\+56|56)?9\\d{8}$')])),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Correo incorrecto.')])),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('anio_publicacion', models.BigIntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(related_name='libros', to='AppCESFAM.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.categoria')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.cliente')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.libro')),
            ],
        ),
        migrations.RemoveField(
            model_name='documento',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='historialdocumento',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historialdocumento',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='HistorialDocumento',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.usuario'),
        ),
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.usuario'),
        ),
    ]
