# Generated by Django 3.2 on 2024-11-29 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCESFAM', '0007_auto_20241128_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El estado solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='contacto',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El número de contacto debe tener entre 8 y 15 dígitos, con o sin prefijo '+' al inicio.", regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato chileno: 12.345.678-9 o 1.234.567-K.', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9kK]$')]),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El tipo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo válido.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='La contraseña debe tener al menos 8 caracteres.'), django.core.validators.RegexValidator(message='La contraseña debe incluir al menos una letra, un número y un símbolo especial.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato chileno: 12.345.678-9 o 1.234.567-K.', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[0-9kK]$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener entre 8 y 15 dígitos, con o sin prefijo '+' al inicio.", regex='^\\+?\\d{8,15}$')]),
        ),
    ]
