# Generated by Django 3.2 on 2024-11-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCESFAM', '0008_auto_20241128_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateField(auto_now_add=True)),
                ('mensaje', models.TextField(default='Documento vencido')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppCESFAM.documento')),
            ],
        ),
    ]
